# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9c9916eb399b65200485b5caa2db973b86ac52e93b8ebcd6e3ed8ff7c5d588e0d8433f4a4e7bc0349d4451853de10a3f478d138ec3d3a48f3035719c380f14

test:
  secret_key_base: d5a6ef90ddce37a1b1c4105b722002bdd4a9923da030fef2e2d2eb591597920c5ad2ad18c4ca2d95cc22e426441a00a143842effb21d3412e3dc59f60951a2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
